import "./globals.css";

// Components
import { ThemeProvider } from "@/components/ThemeProvider";
import SessionWrapper from "@/components/SessionWrapper";
import Header from "@/components/Header";
import { ToastContainer } from "react-toastify";

// Font
import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });

// Metadata
import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionWrapper>
      <html lang="en" suppressHydrationWarning>
        <body className={inter.className}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Header />
            {children}
            <ToastContainer />
          </ThemeProvider>
        </body>
      </html>
    </SessionWrapper>
  );
}
